-- 创建新的表:
CREATE TABLE site_1 LIKE site_1_hour;

DELIMITER //
CREATE TRIGGER tg_hourtime
AFTER INSERT ON site_1
FOR EACH ROW
BEGIN
DECLARE datetimesNow VARCHAR(255);
SET datetimesNow=(SELECT minutes FROM site_1 ORDER BY DATE,minutes,SECOND DESC LIMIT 1);
IF (datetimesNow="0") THEN INSERT INTO site_1_hour (SELECT * FROM site_1 ORDER BY DATE,minutes,SECOND DESC LIMIT 1);
END IF;
END;//

DELIMITER //
CREATE TRIGGER tg_hourtdata
AFTER INSERT ON site_1
FOR EACH ROW
BEGIN
DECLARE datetimesNow VARCHAR(255);
SET datetimesNow=(SELECT minutes FROM site_1 ORDER BY DATE DESC,CAST(minutes AS UNSIGNED) DESC ,CAST(SECOND AS UNSIGNED) DESC LIMIT 1);
IF (datetimesNow="0") THEN INSERT INTO site_1_hourdata (SELECT wholeDate,DATE,temperature,humidity FROM site_1 ORDER BY DATE DESC,CAST(minutes AS UNSIGNED) DESC ,CAST(SECOND AS UNSIGNED) DESC LIMIT 1);
END IF;
END;//